#!/usr/bin/env node
// The Supabase functions bundler cannot import files outside supabase/functions/,
// so the zero-dep parser sources are shared BY COPY. This script owns that copy.
//
//   node scripts/sync-parsers.mjs          # copy packages/parsers/src → supabase/functions/_shared/parsers
//   node scripts/sync-parsers.mjs --check  # exit 1 if the copy is stale (used by CI)
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'packages', 'parsers', 'src');
const DEST = join(ROOT, 'supabase', 'functions', '_shared', 'parsers');
const HEADER = '// AUTO-GENERATED by scripts/sync-parsers.mjs — DO NOT EDIT.\n// Source of truth: packages/parsers/src\n';

function listFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...listFiles(full));
    else out.push(full);
  }
  return out.sort();
}

function expectedContent(srcFile) {
  const body = readFileSync(srcFile, 'utf8');
  return srcFile.endsWith('.ts') ? HEADER + body : body;
}

function sync() {
  rmSync(DEST, { recursive: true, force: true });
  for (const srcFile of listFiles(SRC)) {
    const destFile = join(DEST, relative(SRC, srcFile));
    mkdirSync(dirname(destFile), { recursive: true });
    writeFileSync(destFile, expectedContent(srcFile));
  }
  console.log(`synced ${listFiles(SRC).length} files → ${relative(ROOT, DEST)}`);
}

// git autocrlf gives working-tree files CRLF on Windows; staleness is about
// content, not line endings.
function normalizeEol(s) {
  return s.replace(/\r\n/g, '\n');
}

function check() {
  const srcFiles = listFiles(SRC);
  const problems = [];
  if (!existsSync(DEST)) {
    console.error('parser copy missing — run: node scripts/sync-parsers.mjs');
    process.exit(1);
  }
  const destFiles = listFiles(DEST);
  const expectedDest = new Set(srcFiles.map((f) => join(DEST, relative(SRC, f))));
  for (const d of destFiles) {
    if (!expectedDest.has(d)) problems.push(`extra file in copy: ${relative(ROOT, d)}`);
  }
  for (const s of srcFiles) {
    const d = join(DEST, relative(SRC, s));
    if (!existsSync(d)) problems.push(`missing in copy: ${relative(ROOT, d)}`);
    else if (normalizeEol(readFileSync(d, 'utf8')) !== normalizeEol(expectedContent(s)))
      problems.push(`stale: ${relative(ROOT, d)}`);
  }
  if (problems.length) {
    console.error('parser sync copy is stale:\n  ' + problems.join('\n  '));
    console.error('fix with: node scripts/sync-parsers.mjs');
    process.exit(1);
  }
  console.log('parser sync copy is up to date');
}

if (process.argv.includes('--check')) check();
else sync();
